/**
 * cleanup 阶段顺序常量模块
 *
 * 职责：固定增量登记资源在统一 shutdown 时的业务执行顺序。
 */
import type { CleanupPhase } from '../app/types.js';

export const CLEANUP_PHASE_ORDER: Readonly<Record<CleanupPhase, number>> = {
  CLOSE_TRADING_GATE: 0,
  ABORT_FRESHNESS_WAITING: 10,
  STOP_TIME_WAKEUP_RUNTIME: 20,
  STOP_BUSINESS_EVENT_PROGRAM: 30,
  STOP_TRADING_RISK_EVENT_RUNTIME: 40,
  STOP_MONITOR_QUOTE_EVENT_RUNTIME: 50,
  STOP_MONITOR_DISPLAY_RUNTIME: 60,
  STOP_TRADING_QUOTE_DISPLAY_RUNTIME: 70,
  STOP_SWITCH_WAKEUP_RUNTIME: 80,
  STOP_PERIODIC_SWITCH_WAKEUP_RUNTIME: 90,
  STOP_AUTO_SEARCH_WAKEUP_RUNTIME: 100,
  STOP_SEAT_ACTIVATION_DISPATCHER: 110,
  STOP_MONITOR_TASK_PROCESSOR: 120,
  STOP_SEAT_RUNTIME_CLEANUP_DISPATCHER: 130,
  STOP_BUY_PROCESSOR: 140,
  STOP_SELL_PROCESSOR: 150,
  STOP_ORDER_MONITOR_RUNTIME: 160,
  UNSUBSCRIBE_TRADER_LISTENER: 170,
  STOP_QUOTE_SUBSCRIPTION_RUNTIME: 180,
  STOP_POST_TRADE_CONSISTENCY_RUNTIME: 190,
  DESTROY_DELAYED_SIGNAL_VERIFIER: 200,
  CLEAR_INDICATOR_CACHE: 210,
  CLEAR_MONITOR_SNAPSHOT: 220,
  RESET_MARKET_DATA_RUNTIME: 230,
};
