/**
 * 配置环境测试工厂
 *
 * 负责为配置解析与校验测试提供完整的单实例 env 基线，
 * 避免测试因缺失必填配置而意外依赖代码默认值。
 */

const COMMON_REQUIRED_ENV = {
  LONGBRIDGE_AUTH_MODE: 'oauth',
  LONGBRIDGE_CLIENT_ID: 'client-id',
  ORDER_OWNERSHIP_MAPPING: 'HSI',
  DEBUG: 'false',
  DOOMSDAY_PROTECTION: 'true',
  MORNING_OPENING_PROTECTION_ENABLED: 'false',
  AFTERNOON_OPENING_PROTECTION_ENABLED: 'false',
  BUY_ORDER_TIMEOUT_ENABLED: 'true',
  BUY_ORDER_TIMEOUT_SECONDS: '180',
  SELL_ORDER_TIMEOUT_ENABLED: 'false',
  SELL_ORDER_TIMEOUT_SECONDS: '180',
  ORDER_MONITOR_PRICE_UPDATE_INTERVAL: '3',
  ALLOW_BUY_ORDER_TRACKING_ABOVE_INITIAL_PRICE: 'false',
  TRADING_ORDER_TYPE: 'ELO',
  LIQUIDATION_ORDER_TYPE: 'ELO',
  TARGET_NOTIONAL: '10000',
  MAX_POSITION_NOTIONAL: '100000',
  MAX_UNREALIZED_LOSS_PER_SYMBOL: '2200',
  BUY_INTERVAL_SECONDS: '120',
  LIQUIDATION_TRIGGER_LIMIT: '2',
  REGIME_THRESHOLDS_ATR_SHORT_PERIOD: '5',
  REGIME_THRESHOLDS_ATR_LONG_PERIOD: '30',
  REGIME_THRESHOLDS_RV_QUANTILE_WINDOW_DAYS: '20',
  REGIME_THRESHOLDS_TREND_ON_VOL_EXPANSION: '1.2',
  REGIME_THRESHOLDS_TREND_OFF_VOL_EXPANSION: '0.9',
  REGIME_THRESHOLDS_EXTREME_VOL_EXPANSION: '1.8',
  REGIME_THRESHOLDS_TREND_ON_VOL_QUANTILE: '0.7',
  REGIME_THRESHOLDS_TREND_OFF_VOL_QUANTILE: '0.4',
  REGIME_THRESHOLDS_EXTREME_VOL_QUANTILE: '0.95',
  TREND_SCORE_THRESHOLDS_W15: '0.25',
  TREND_SCORE_THRESHOLDS_W30: '0.35',
  TREND_SCORE_THRESHOLDS_W60: '0.4',
  TREND_SCORE_THRESHOLDS_CLASSIFICATION_THRESHOLD: '0.8',
  TREND_SCORE_THRESHOLDS_ENTRY_THRESHOLD: '0.9',
  TREND_SCORE_THRESHOLDS_EXIT_THRESHOLD: '0.35',
  TREND_SCORE_THRESHOLDS_REVERSE_INVALIDATION_THRESHOLD: '0.5',
  ER_THRESHOLDS_ER15_ENTRY_MIN: '0.4',
  ER_THRESHOLDS_ER30_ENTRY_MIN: '0.35',
  ER_THRESHOLDS_ER15_EXIT_MAX: '0.25',
  ER_THRESHOLDS_ER30_EXIT_MAX: '0.2',
  ER_THRESHOLDS_STRONG_TREND_ER_FLOOR: '0.45',
  VWAP_CONFIRM_RULES_DISTANCE_BAND_ATR: '0.1',
  VWAP_CONFIRM_RULES_SLOPE_WINDOW_BARS: '5',
  VWAP_CONFIRM_RULES_MAX_CROSS_COUNT_LAST10M: '2',
  OPENING_STRUCTURE_RULES_OR_WINDOW_MINUTES: '20',
  OPENING_STRUCTURE_RULES_MORNING_NOISE_WINDOW_MINUTES: '20',
  OPENING_STRUCTURE_RULES_AFTERNOON_NOISE_WINDOW_MINUTES: '15',
  OPENING_STRUCTURE_RULES_BREAKOUT_SCORE_MIN: '0.8',
  OPENING_STRUCTURE_RULES_OUTSIDE_PERSISTENCE_WINDOW_BARS: '5',
  OPENING_STRUCTURE_RULES_OUTSIDE_PERSISTENCE_MIN: '0.6',
  OPENING_STRUCTURE_RULES_RETEST_TOLERANCE_ATR: '0.2',
  OPENING_STRUCTURE_RULES_CONFIRM_BARS: '2',
  PM_CONTINUATION_RULES_AM_MOVE_Z_MIN: '0.8',
  PM_CONTINUATION_RULES_MIDDAY_HOLD_MIN: '0.6',
  PM_CONTINUATION_RULES_PM_RE_EXPANSION_TREND_SCORE_MIN: '0.9',
  PM_CONTINUATION_RULES_PM_RE_EXPANSION_ER15_MIN: '0.35',
  PM_CONTINUATION_RULES_PM_CONFIRM_CUTOFF_TIME: '13:30',
  INSTRUMENT_ADAPTATION_RULES_BULL_BUY_MIN_DISTANCE_PCT: '0.35',
  INSTRUMENT_ADAPTATION_RULES_BEAR_BUY_MAX_DISTANCE_PCT: '-0.35',
  INSTRUMENT_ADAPTATION_RULES_BULL_LIQUIDATION_DISTANCE_PCT: '0.2',
  INSTRUMENT_ADAPTATION_RULES_BEAR_LIQUIDATION_DISTANCE_PCT: '-0.2',
} as const satisfies Readonly<Record<string, string>>;

const AUTO_SEARCH_REQUIRED_ENV = {
  AUTO_SEARCH_MIN_DISTANCE_PCT_BULL: '0.8',
  AUTO_SEARCH_MIN_DISTANCE_PCT_BEAR: '-0.8',
  AUTO_SEARCH_MIN_TURNOVER_PER_MINUTE_BULL: '300000',
  AUTO_SEARCH_MIN_TURNOVER_PER_MINUTE_BEAR: '300000',
  AUTO_SEARCH_EXPIRY_MIN_MONTHS: '6',
  AUTO_SEARCH_OPEN_DELAY_MINUTES: '5',
  SWITCH_INTERVAL_MINUTES: '0',
  SWITCH_DISTANCE_RANGE_BULL: '0.4,1.5',
  SWITCH_DISTANCE_RANGE_BEAR: '-1.5,-0.4',
} as const satisfies Readonly<Record<string, string>>;

export function createRequiredStaticEnv(
  overrides: Readonly<Record<string, string>> = {},
): NodeJS.ProcessEnv {
  return {
    ...COMMON_REQUIRED_ENV,
    SEAT_MODE: 'static',
    LONG_SYMBOL: 'BULL.HK',
    SHORT_SYMBOL: 'BEAR.HK',
    ...overrides,
  };
}

export function createRequiredAutoEnv(
  overrides: Readonly<Record<string, string>> = {},
): NodeJS.ProcessEnv {
  return {
    ...COMMON_REQUIRED_ENV,
    ...AUTO_SEARCH_REQUIRED_ENV,
    SEAT_MODE: 'auto',
    ...overrides,
  };
}
